### ISSUE TITLE
[Request] add docker-compose to manage volumes

### ISSUE THREAD

**Issue by rafonsecad** [P0cL4bs/wifipumpkin3#56]
On the current wifipumpkin version, the docker container works great. Nevertheless it also has some limitations, specially in these two cases:

- Every addition or modification of any pulp would mean to build the entire docker image again. This also applies when adding new plugins or changes in the configuration files.
- There is no way to save any logs inside the docker container. Once the container stops, any data inside the container is destroyed.

Of course, these two issues can be solved simply by adding volumes, but to improve the management of the volumes it would be great to add a docker-compose file to the project. I've been making some tests and the docker-compose.yml looks like this:

```
version: '3.2'
services:
  wifipumpkin:
        build:
                context: .
        privileged: true
        network_mode: "host"
        volumes:
                - type: bind
                  source: ./scripts
                  target: /root/.config/wifipumpkin3/scripts
                - type: bind
                  source: ./logs
                  target: /root/.config/wifipumpkin3/logs
                - type: bind
                  source: ./config
                  target: /root/.config/wifipumpkin3/config
```
this file should be on the same folder level as the Dockerfile. Once installed docker-compose, one can run
```
$ docker-compose build wifipumpkin                    # To build the image
$ sudo docker-compose run wifipumpkin wifipumpkin3     # To run the image
```
As you can see in the docker-compose.yml, there are three volumes that points to folders in the project. We can add/edit  configurations or pulps adding them in config or scripts folders respectively, and to view the logs in logs folder.

I also made a tiny change in the Dockerfile to set the working directory to /root/.config/wifipumpkin3, so it would be easier to call the pulps

```
...
RUN python3.7 setup.py install
#CMD /usr/local/bin/wifipumpkin3 -m docker # I don't know what this line is used for, I always get an error when I try to run it and in the current docker documentation it doesn't get executed anyways.
WORKDIR /root/.config/wifipumpkin3
CMD /usr/local/bin/wifipumpkin3
```
The command to call a pulp would be:
```
$ sudo docker-compose run wifipumpkin wifipumpkin3 --pulp scripts/my_pulp.pulp
```

I hope you like this request, if you have any questions, please don't hesitate to ask. This project is really cool, thanks for your dedication.
